# Variables

# default versions
KEYCLOAK_VERSION="${KEYCLOAK_VERSION:-6.0.1}"
OPENJDK_VERSION="${OPENJDK_VERSION:-11+28}"
JDBC_MYSQL_VERSION="${JDBC_MYSQL_VERSION:-5.1.46}"

KEYCLOAK_DIR="${DEPS_DIR}/${DEPS_IDX}/keycloak"
OPENJDK_DIR="${DEPS_DIR}/${DEPS_IDX}/jdk"