# Variables

# default versions
KEYCLOAK_VERSION="${KEYCLOAK_VERSION:-6.0.1}"
OPENJDK_VERSION="${OPENJDK_VERSION:-11+28}"

KEYCLOAK_DIR="${DEPS_DIR}/${DEPS_IDX}/jboss"
OPENJDK_DIR="${DEPS_DIR}/${DEPS_IDX}/jdk"